export type Qualification = {
  id: string;
  title: string;
  provider: string;
  providerLogo?: string;
  nfqLevel?: number;
  pathway: 'University' | 'Apprenticeship' | 'Further Education' | 'Bootcamp';
  delivery: 'On-campus' | 'Online' | 'Hybrid';
  duration: string; // e.g. '4 years', '12 weeks'
  location?: string;
  costRange?: string;
  url: string;
  applyUrl?: string;
  outcomes: string[]; // career titles
  summary?: string;
  modules?: string[];
  entryRequirements?: string[];
  startDates?: string[];
  tags?: string[];
  category: 'Computer Science' | 'Engineering' | 'Information Science' | 'Data Science' | 'AI' | 'Software Development' | 'Cyber Security';
  caoCode?: string;
  videoUrl?: string;
};

export const qualifications: Qualification[] = [
  // Computer Science Courses
  {
    id: 'ug-cs-it-gy350',
    title: 'BSc (Hons) in Computer Science and Information Technology',
    provider: 'University of Galway',
    providerLogo: '/logos/university-of-galway.png',
    nfqLevel: 8,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '4 years',
    location: 'Galway',
    caoCode: 'GY350',
    url: 'https://www.universityofgalway.ie/courses/undergraduate-courses/computer-science-and-information-technology.html',
    videoUrl: 'https://www.youtube.com/watch?v=example1',
    outcomes: ['Software Developer', 'Systems Analyst', 'Data Analyst'],
    summary: 'Degree covering software engineering, algorithms, databases, and networks with strong industry links.',
    modules: ['Programming', 'Web Development', 'Databases', 'Networks'],
    entryRequirements: ['Leaving Cert Maths (H5)'],
    category: 'Computer Science',
  },
  {
    id: 'ug-it-arts-gy101',
    title: 'BA in IT (subject for Arts Students)',
    provider: 'University of Galway',
    providerLogo: '/logos/university-of-galway.png',
    nfqLevel: 8,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '4 years',
    location: 'Galway',
    caoCode: 'GY101',
    url: 'https://www.universityofgalway.ie/courses/undergraduate-courses/it-as-a-subject-for-arts-students.html',
    outcomes: ['IT Consultant', 'Business Analyst', 'Project Manager'],
    category: 'Computer Science',
  },
  {
    id: 'atu-cs-au361',
    title: 'BSc (Hons) in Computer Science',
    provider: 'Atlantic Technological University',
    providerLogo: '/logos/atu-logo.png',
    nfqLevel: 8,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '3 years',
    location: 'Donegal - Letterkenny Campus',
    caoCode: 'AU361',
    url: 'https://www.atu.ie/courses/bachelor-of-science-honours-computer-science',
    videoUrl: 'https://www.youtube.com/watch?v=example2',
    outcomes: ['Software Developer', 'Cloud Engineer'],
    category: 'Computer Science',
  },
  {
    id: 'atu-applied-computing-au360',
    title: 'BSc (Hons) Computing in Applied Computing',
    provider: 'Atlantic Technological University',
    providerLogo: '/logos/atu-logo.png',
    nfqLevel: 8,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '4 years',
    location: 'Donegal - Letterkenny Campus',
    caoCode: 'AU360',
    url: 'https://www.atu.ie/courses/computing-in-applied-computing',
    videoUrl: 'https://www.youtube.com/watch?v=example3',
    outcomes: ['Software Developer', 'Application Developer'],
    category: 'Computer Science',
  },
  {
    id: 'ul-cs-lm121',
    title: 'Computer Science (Common Entry)',
    provider: 'University of Limerick',
    providerLogo: '/logos/ul-logo.png',
    nfqLevel: 8,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '4 years',
    location: 'Limerick',
    caoCode: 'LM121',
    url: 'https://www.ul.ie/courses/computer-science-common-entry',
    videoUrl: 'https://www.youtube.com/watch?v=example4',
    outcomes: ['Software Developer', 'DevOps Engineer'],
    category: 'Computer Science',
  },
  {
    id: 'ucc-cs-ck401',
    title: 'Computer Science',
    provider: 'University College Cork',
    providerLogo: '/logos/ucc-logo.png',
    nfqLevel: 8,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '4 years',
    location: 'Cork',
    caoCode: 'CK401',
    url: 'https://www.ucc.ie/en/ck401/',
    outcomes: ['Software Developer', 'Systems Analyst'],
    category: 'Computer Science',
  },
  {
    id: 'dcu-cs-dc121',
    title: 'BSc in Computer Science',
    provider: 'Dublin City University',
    providerLogo: '/logos/dcu-logo.png',
    nfqLevel: 8,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '4 years',
    location: 'Dublin',
    caoCode: 'DC121',
    url: 'https://www.dcu.ie/courses/undergraduate/school-computing/bsc-computer-science',
    videoUrl: 'https://www.youtube.com/watch?v=example5',
    outcomes: ['Software Developer', 'Computer Systems Analyst'],
    category: 'Computer Science',
  },
  {
    id: 'ucd-cs-cssa',
    title: 'Computer Science',
    provider: 'University College Dublin',
    providerLogo: '/logos/ucd-logo.png',
    nfqLevel: 8,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '4 years',
    location: 'Dublin',
    caoCode: 'CSSA',
    url: 'https://www.ucd.ie/courses/cssa/',
    outcomes: ['Software Developer', 'Computer Scientist'],
    category: 'Computer Science',
  },

  // Engineering Courses
  {
    id: 'ug-eng-gy406',
    title: 'Bachelor and Master of Engineering (Electronic and Computer)',
    provider: 'University of Galway',
    providerLogo: '/logos/university-of-galway.png',
    nfqLevel: 9,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '5 years (4+1)',
    location: 'Galway',
    caoCode: 'GY406',
    url: 'https://www.universityofgalway.ie/courses/undergraduate-courses/bachelor-of-engineering-electronic-and-computer.html',
    videoUrl: 'https://www.youtube.com/watch?v=example6',
    outcomes: ['Electronic Engineer', 'Computer Engineer', 'Software Engineer'],
    category: 'Engineering',
  },
  {
    id: 'ucd-eng-dn150',
    title: 'Bachelor of Engineering',
    provider: 'University College Dublin',
    providerLogo: '/logos/ucd-logo.png',
    nfqLevel: 8,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '4 years',
    location: 'Dublin',
    caoCode: 'DN150',
    url: 'https://www.ucd.ie/courses/dn150/',
    videoUrl: 'https://www.youtube.com/watch?v=example7',
    outcomes: ['Electrical Engineer', 'Electronic Engineer'],
    category: 'Engineering',
  },
  {
    id: 'ul-eng-lm118',
    title: 'Bachelor of Engineering in Electronic and Computer Engineering',
    provider: 'University of Limerick',
    providerLogo: '/logos/ul-logo.png',
    nfqLevel: 8,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '4 years',
    location: 'Limerick',
    caoCode: 'LM118',
    url: 'https://www.ul.ie/courses/bachelor-master-of-engineering-in-electronic-and-computer-engineering',
    videoUrl: 'https://www.youtube.com/watch?v=example8',
    outcomes: ['Electronic Engineer', 'Computer Engineer'],
    category: 'Engineering',
  },
  {
    id: 'ucc-eng-ck600',
    title: 'Bachelor of Engineering',
    provider: 'University College Cork',
    providerLogo: '/logos/ucc-logo.png',
    nfqLevel: 8,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '4 years',
    location: 'Cork',
    caoCode: 'CK600',
    url: 'https://www.ucc.ie/en/ck600/',
    outcomes: ['Electrical Engineer', 'Electronic Engineer'],
    category: 'Engineering',
  },
  {
    id: 'tus-comp-eng-us714',
    title: 'Bachelor of Computer Engineering',
    provider: 'Technological University of the Shannon',
    providerLogo: '/logos/tus-logo.png',
    nfqLevel: 8,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '3 years',
    location: 'Shannon',
    caoCode: 'US714',
    url: 'https://www.tus.ie/courses/computer-engineering-beng/',
    outcomes: ['Computer Engineer', 'Software Engineer'],
    category: 'Engineering',
  },
  {
    id: 'maynooth-csse-mh602',
    title: 'BSc in Computer Science and Software Engineering',
    provider: 'Maynooth University',
    providerLogo: '/logos/maynooth-logo.png',
    nfqLevel: 8,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '4 years',
    location: 'Maynooth',
    caoCode: 'MH602',
    url: 'https://www.maynoothuniversity.ie/courses/computer-science-software-engineering',
    outcomes: ['Software Engineer', 'Computer Scientist'],
    category: 'Engineering',
  },

  // Data Science Courses
  {
    id: 'dcu-ds-dc123',
    title: 'BSc in Data Science',
    provider: 'Dublin City University',
    providerLogo: '/logos/dcu-logo.png',
    nfqLevel: 8,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '4 years',
    location: 'Dublin',
    caoCode: 'DC123',
    url: 'https://www.dcu.ie/courses/undergraduate/school-computing/bsc-data-science',
    videoUrl: 'https://www.youtube.com/watch?v=example9',
    outcomes: ['Data Scientist', 'Data Analyst', 'Business Analyst'],
    category: 'Data Science',
  },
  {
    id: 'ucd-ds-cssc',
    title: 'Computer Science with Data Science',
    provider: 'University College Dublin',
    providerLogo: '/logos/ucd-logo.png',
    nfqLevel: 8,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '4 years',
    location: 'Dublin',
    caoCode: 'CSSC',
    url: 'https://www.ucd.ie/courses/cssc/',
    outcomes: ['Data Scientist', 'Computer Scientist'],
    category: 'Data Science',
  },
  {
    id: 'nci-ds-nc025',
    title: 'Bachelor (Honours) in Data Science',
    provider: 'National College of Ireland',
    providerLogo: '/logos/nci-logo.png',
    nfqLevel: 8,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '4 years',
    location: 'Dublin',
    caoCode: 'NC025',
    url: 'https://www.ncirl.ie/courses/bsc-honours-data-science',
    videoUrl: 'https://www.youtube.com/watch?v=example10',
    outcomes: ['Data Scientist', 'Data Analyst'],
    category: 'Data Science',
  },
  {
    id: 'maynooth-ds-mh207',
    title: 'Bachelor of Data Science',
    provider: 'Maynooth University',
    providerLogo: '/logos/maynooth-logo.png',
    nfqLevel: 8,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '4 years',
    location: 'Maynooth',
    caoCode: 'MH207',
    url: 'https://www.maynoothuniversity.ie/courses/data-science',
    outcomes: ['Data Scientist', 'Data Analyst'],
    category: 'Data Science',
  },
  {
    id: 'tud-ds-ai-tu850',
    title: 'BSc (Hons) in Data Science and Artificial Intelligence',
    provider: 'Technological University Dublin',
    providerLogo: '/logos/tud-logo.png',
    nfqLevel: 8,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '4 years',
    location: 'Dublin',
    caoCode: 'TU850',
    url: 'https://www.tudublin.ie/courses/course/computer-science/data-science-and-artificial-intelligence-tu850/',
    videoUrl: 'https://www.youtube.com/watch?v=example11',
    outcomes: ['Data Scientist', 'AI Engineer', 'Machine Learning Engineer'],
    category: 'Data Science',
  },

  // AI Courses
  {
    id: 'atu-ds-ai-au363',
    title: 'BSc (Hons) Computing in Data Science and Artificial Intelligence',
    provider: 'Atlantic Technological University',
    providerLogo: '/logos/atu-logo.png',
    nfqLevel: 8,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '4 years',
    location: 'Donegal - Letterkenny Campus',
    caoCode: 'AU363',
    url: 'https://www.atu.ie/courses/computing-in-data-science-and-artificial-intelligence',
    videoUrl: 'https://www.youtube.com/watch?v=example12',
    outcomes: ['AI Engineer', 'Data Scientist', 'Machine Learning Engineer'],
    category: 'AI',
  },
  {
    id: 'ul-ai-ml-lm174',
    title: 'Bachelor/Master of Science in Artificial Intelligence and Machine Learning',
    provider: 'University of Limerick',
    providerLogo: '/logos/ul-logo.png',
    nfqLevel: 9,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '4+1 years',
    location: 'Limerick',
    caoCode: 'LM174',
    url: 'https://www.ul.ie/courses/bachelor-master-of-science-in-artificial-intelligence-and-machine-learning',
    videoUrl: 'https://www.youtube.com/watch?v=example13',
    outcomes: ['AI Researcher', 'Machine Learning Engineer', 'Data Scientist'],
    category: 'AI',
  },

  // Software Development Courses
  {
    id: 'mtu-sd-mt800',
    title: 'BSc (Hons) in Software Development',
    provider: 'Munster Technological University',
    providerLogo: '/logos/mtu-logo.png',
    nfqLevel: 8,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '4 years',
    location: 'Cork',
    caoCode: 'MT800',
    url: 'https://www.mtu.ie/courses/bsc-hons-software-development/',
    outcomes: ['Software Developer', 'Web Developer'],
    category: 'Software Development',
  },
  {
    id: 'mtu-sd-mt700',
    title: 'BSc in Software Development',
    provider: 'Munster Technological University',
    providerLogo: '/logos/mtu-logo.png',
    nfqLevel: 7,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '3 years',
    location: 'Cork',
    caoCode: 'MT700',
    url: 'https://www.mtu.ie/courses/bsc-software-development/',
    outcomes: ['Software Developer', 'Junior Developer'],
    category: 'Software Development',
  },
  {
    id: 'tus-sd-us820',
    title: 'BSc (Hons) in Software Development',
    provider: 'Technological University of the Shannon',
    providerLogo: '/logos/tus-logo.png',
    nfqLevel: 8,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '4 years',
    location: 'Shannon',
    caoCode: 'US820',
    url: 'https://www.tus.ie/courses/software-development-bsc-hons/',
    outcomes: ['Software Developer', 'Application Developer'],
    category: 'Software Development',
  },
  {
    id: 'setu-sd-se603',
    title: 'BSc (Hons) in Software Development',
    provider: 'South East Technological University',
    providerLogo: '/logos/setu-logo.png',
    nfqLevel: 8,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '4 years',
    location: 'Waterford',
    caoCode: 'SE603',
    url: 'https://www.setu.ie/courses/bsc-hons-software-development',
    outcomes: ['Software Developer', 'Web Developer'],
    category: 'Software Development',
  },
  {
    id: 'atu-sd-au676',
    title: 'BSc (Hons) in Computing in Software Development',
    provider: 'Atlantic Technological University',
    providerLogo: '/logos/atu-logo.png',
    nfqLevel: 8,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '4 years',
    location: 'Galway Campus',
    caoCode: 'AU676',
    url: 'https://www.atu.ie/courses/computing-in-software-development',
    videoUrl: 'https://www.youtube.com/watch?v=example14',
    outcomes: ['Software Developer', 'Application Developer'],
    category: 'Software Development',
  },
  {
    id: 'atu-sd-au576',
    title: 'BSc in Computing in Software Development',
    provider: 'Atlantic Technological University',
    providerLogo: '/logos/atu-logo.png',
    nfqLevel: 7,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '3 years',
    location: 'Galway Campus',
    caoCode: 'AU576',
    url: 'https://www.atu.ie/courses/computing-in-software-development',
    outcomes: ['Software Developer', 'Junior Developer'],
    category: 'Software Development',
  },
  {
    id: 'dkit-sd-dk821',
    title: 'Bachelor (Honours) in Computing in Software Development',
    provider: 'Dundalk Institute of Technology',
    providerLogo: '/logos/dkit-logo.png',
    nfqLevel: 8,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '4 years',
    location: 'Dundalk',
    caoCode: 'DK821',
    url: 'https://www.dkit.ie/courses/computing-software-development',
    videoUrl: 'https://www.youtube.com/watch?v=example15',
    outcomes: ['Software Developer', 'Application Developer'],
    category: 'Software Development',
  },

  // Cyber Security Courses
  {
    id: 'tus-cs-us819',
    title: 'BSc (Hons) in Software Development with Cyber Security',
    provider: 'Technological University of the Shannon',
    providerLogo: '/logos/tus-logo.png',
    nfqLevel: 8,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '4 years',
    location: 'Shannon',
    caoCode: 'US819',
    url: 'https://www.tus.ie/courses/software-development-cyber-security-bsc-hons/',
    outcomes: ['Cyber Security Engineer', 'Software Developer'],
    category: 'Cyber Security',
  },
  {
    id: 'tus-cn-cs-us827',
    title: 'BSc (Hons) in Computer Networks & Cyber Security',
    provider: 'Technological University of the Shannon',
    providerLogo: '/logos/tus-logo.png',
    nfqLevel: 8,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '4 years',
    location: 'Shannon',
    caoCode: 'US827',
    url: 'https://www.tus.ie/courses/computer-networks-cyber-security-bsc-hons/',
    outcomes: ['Cyber Security Analyst', 'Network Engineer'],
    category: 'Cyber Security',
  },
  {
    id: 'atu-cn-cs-au956',
    title: 'BSc (Hons) in Computer Networks and Cyber Security',
    provider: 'Atlantic Technological University',
    providerLogo: '/logos/atu-logo.png',
    nfqLevel: 8,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '4 years',
    location: 'Sligo Campus',
    caoCode: 'AU956',
    url: 'https://www.atu.ie/courses/computer-networks-and-cyber-security',
    videoUrl: 'https://www.youtube.com/watch?v=example16',
    outcomes: ['Cyber Security Analyst', 'Network Security Engineer'],
    category: 'Cyber Security',
  },
  {
    id: 'ul-cs-it-lm121',
    title: 'BSc in Cyber Security and IT Forensics',
    provider: 'University of Limerick',
    providerLogo: '/logos/ul-logo.png',
    nfqLevel: 8,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '4 years',
    location: 'Limerick',
    caoCode: 'LM121',
    url: 'https://www.ul.ie/courses/bachelor-of-science-in-cyber-security-and-it-forensics',
    videoUrl: 'https://www.youtube.com/watch?v=example17',
    outcomes: ['Cyber Security Analyst', 'Digital Forensics Specialist'],
    category: 'Cyber Security',
  },
  {
    id: 'setu-cc-se606',
    title: 'BSc (Hons) in Cybercrime and IT Security',
    provider: 'South East Technological University',
    providerLogo: '/logos/setu-logo.png',
    nfqLevel: 8,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '4 years',
    location: 'Carlow Campus',
    caoCode: 'SE606',
    url: 'https://www.setu.ie/courses/bsc-hons-cybercrime-it-security',
    outcomes: ['Cyber Security Analyst', 'IT Security Specialist'],
    category: 'Cyber Security',
  },
  {
    id: 'tud-df-cs-tu863',
    title: 'BSc (Hons) in Computing in Digital Forensics and Cyber Security',
    provider: 'Technological University Dublin',
    providerLogo: '/logos/tud-logo.png',
    nfqLevel: 8,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '4 years',
    location: 'Dublin',
    caoCode: 'TU863',
    url: 'https://www.tudublin.ie/courses/course/computer-science/digital-forensics-and-cyber-security-tu863/',
    videoUrl: 'https://www.youtube.com/watch?v=example18',
    outcomes: ['Digital Forensics Specialist', 'Cyber Security Analyst'],
    category: 'Cyber Security',
  },
  {
    id: 'mtu-it-cs-mt805',
    title: 'BSc (Hons) in IT Management and Cybersecurity',
    provider: 'Munster Technological University',
    providerLogo: '/logos/mtu-logo.png',
    nfqLevel: 8,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '4 years',
    location: 'Cork',
    caoCode: 'MT805',
    url: 'https://www.mtu.ie/courses/bsc-hons-it-management-cybersecurity/',
    outcomes: ['IT Manager', 'Cyber Security Manager'],
    category: 'Cyber Security',
  },
  {
    id: 'mtu-it-cs-mt705',
    title: 'BSc in Information Technology and Cybersecurity',
    provider: 'Munster Technological University',
    providerLogo: '/logos/mtu-logo.png',
    nfqLevel: 7,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '3 years',
    location: 'Cork',
    caoCode: 'MT705',
    url: 'https://www.mtu.ie/courses/bsc-information-technology-cybersecurity/',
    outcomes: ['IT Specialist', 'Cyber Security Technician'],
    category: 'Cyber Security',
  },

  // Information Science Courses
  {
    id: 'setu-it-se613',
    title: 'BSc in Information Technology',
    provider: 'South East Technological University',
    providerLogo: '/logos/setu-logo.png',
    nfqLevel: 7,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '3 years',
    location: 'Waterford Campus',
    caoCode: 'SE613',
    url: 'https://www.setu.ie/courses/bsc-information-technology',
    outcomes: ['IT Specialist', 'Systems Administrator'],
    category: 'Information Science',
  },
  {
    id: 'setu-itm-se601',
    title: 'BSc (Hons) in Information Technology Management',
    provider: 'South East Technological University',
    providerLogo: '/logos/setu-logo.png',
    nfqLevel: 8,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '4 years',
    location: 'Carlow Campus',
    caoCode: 'SE601',
    url: 'https://www.setu.ie/courses/bsc-hons-information-technology-management',
    outcomes: ['IT Manager', 'Project Manager'],
    category: 'Information Science',
  },
  {
    id: 'setu-itm-se614',
    title: 'BSc in Information Technology Management',
    provider: 'South East Technological University',
    providerLogo: '/logos/setu-logo.png',
    nfqLevel: 7,
    pathway: 'University',
    delivery: 'On-campus',
    duration: '3 years',
    location: 'Carlow Campus',
    caoCode: 'SE614',
    url: 'https://www.setu.ie/courses/bsc-information-technology-management',
    outcomes: ['IT Specialist', 'Business Analyst'],
    category: 'Information Science',
  },
];


